### PR TITLE
Link icons

### PR DESCRIPTION
**Pull request by oliver-norden**
This pull request would add the ability to utilize icons (images) in link. The user would be able to select wether to only show the title (current behavior), or an icon with a custom class, or both.

Let me know if there is anything that needs to be changed or if the feature is not desired.

Many thanks!

### CODE REVIEW

**Comment by elliot-sawyer** [comment]
Thanks @oliver-norden , I'll have a look at it sometime this weekend or early next week!

**Comment by gorriecoe** [comment]
I'm not really sure this would be useful for general usage.  Can we try separate this to a extension module?

**Comment by gorriecoe** [comment]
I hate to repeat this but I'm not really sure this would be useful for general usage. Can we try separate this to a extension module?

**Comment by oliver-norden** [comment]
Hello, I understand. I will have to take a look to see what could be done

**Comment by gorriecoe** [comment]
Cool =).  Take a look at https://github.com/gorriecoe/silverstripe-link/blob/master/src/extensions/AutomaticMarkupID.php and https://github.com/gorriecoe/silverstripe-link/blob/master/src/extensions/DefineableMarkupID.php as an example.

**Comment by gorriecoe** [comment]
That may help you out.

**Review by elliot-sawyer — COMMENTED** [review]
I agree with @gorriecoe, it would be better to keep this module as lean as possible. It should do one thing really well, but allow functionality to be extended. 

Create your own module that applies your functionality via a DataExtension. Something like this can be applied to Link as an extension:

```php
//use statements omitted
class LinkIconExtension extends DataExtension 
{
    private static $db = [...]; // these get merged with Link's $db array
    private static $has_one = [...]; // these get merged with Link's $has_one
    private static $defaults = [...];
    public function updateCMSFields(FieldList $fields)
    {
        //add your CMS fields in here
    }
}
```

I tend to leave the application of extensions up to the developer, but if you wanted to apply it automatically when your module is installed, you can include `_config/config.yml` in your module:

```yml
Name\Space\GorrieCoe\Link:
  extensions:
    - YourNameSpace\YourModule\LinkIconExtension
```

You would then include a templates folder in your module.

A few other points to consider when refactoring this as an extension:
- You should never change the package name in composer.json. It will break existing installations. You can do this on your own module, then check out this one alongside it.
- There's no restrictions on the upload type: at a minimum, it should be an `Image::class`, or a `File::class` with certain categories allowed. I assumed the use-case here is for images and SVG files: you should make that clear in the documentation. Consider adding a setDescription() field to it.
- There's no documentation on how to use the new feature: what file types are allowed? What should a dev do, or not do, to use the feature?
- Add as many tests as possible!  :-D

**Comment by gorriecoe** [comment]
@oliver-norden I have made an module to achieve this functionality.  https://github.com/gorriecoe/silverstripe-linkicon.  Use it as a working example.  Its very basic but combine this with the use of [selectable styles](https://github.com/gorriecoe/silverstripe-link#cms-selectable-style) to hide the title and you should achieve what you want without writing to the core link module.

**Comment by gorriecoe** [comment]
## Link icon only

Step by step instructions to setup icon only links.

```
composer require gorriecoe/silverstripe-link gorriecoe/silverstripe-linkicon
```

In your config.yml add the following:

```yml
gorriecoe\Link\Models\Link:
  icon_asset_folder: 'SomeFolderName' // Defaults to 'Icons'
  icon_tab: 'SomeTabName' // Defaults to 'Main'
  styles:
    icononly: Icon only
```

Create a `Link_icononly.ss` file in your theme includes directory with the following:

```
<% if LinkURL %>
    <a{$IDAttr}{$ClassAttr} href="{$LinkURL}"{$TargetAttr}>
        <img src="{$Icon.Link}" alt="{$Title}" />
    </a>
<% end_if %>
```

**Pull request closed without merging**
