### PR TITLE
Allow Silverstripe 5

### PR DESCRIPTION
**Pull request by jsirish**
Tested on 5.0.0-beta1 and all seems to work well.

### CODE REVIEW

**Comment by matthewrayner** [comment]
@jsirish FYI you will need to update the `unclecheese/display-logic` version constraint to `^3`

**Comment by jsirish** [comment]
@matthewrayner should be all set, thanks!

**Comment by obj63mc** [comment]
Any chance this can be merged?

**Comment by elliot-sawyer** [comment]
Works great, merging.  Thanks for your contributions!

**Comment by oddnoc** [comment]
unclecheese/display-logic 3 requires framework 5, so there's little point in allowing framework 4

**Pull request merged**
